# Generated by Django 2.2 on 2020-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bankname',
            field=models.CharField(blank=True, default='nill', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='bankname',
            field=models.CharField(blank=True, default='nill', max_length=50, null=True),
        ),
    ]
