# Generated by Django 2.2 on 2020-09-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200925_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='chequeordd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='dateinbank',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='bankname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='chequeordd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='dateinbank',
            field=models.DateField(blank=True, null=True),
        ),
    ]
