# Generated by Django 2.2 on 2020-09-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200930_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='chequeordd',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
