# Generated by Django 2.2 on 2020-09-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200930_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dateinbank',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='dateinbank',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
