# Generated by Django 2.2 on 2020-10-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('cashinhand', models.IntegerField(blank=True, null=True)),
                ('cashatbank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
