# Generated by Django 2.2 on 2020-11-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201030_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='cashatbankexp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
