# Generated by Django 2.2 on 2020-11-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_reportdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reportdate',
        ),
    ]
